ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shops.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

josh-shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart', include('cart.urls')),
    path('orders/', include('order.urls')),
    path('accounts/', include('user.urls')),
    path('', include('shops.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shops/urls.py
from django.urls import path
from . import views

app_name = 'shops'

urlpatterns = [
    path('', views.product_list, name='Home'),
    path('contact me/', views.contact, name='Contact'),
    path('reach me/', views.feedback, name='reach'),

]

shops/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone


class Category(models.Model):
    name = models.CharField(max_length=15, db_index=True)
    slug = models.SlugField(max_length=15, unique=True, db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shops:product_list_by_category', args=[self.slug])



class Contacts(models.Model):
    user_name = models.CharField(max_length=20, blank=False)
    email = models.EmailField()
    mobile_number = models.CharField(max_length=20, blank=True, null=True)
    message = models.TextField(max_length=100)
    submitted_date = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ('submitted_date',)

    def __str__(self):
        return self.user_name

    pass



# Create your models here.

shops/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category
from .models import Contacts


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
    context = {
        'category': category,
        'categories': categories,

    }
    return render(request, 'shop/product/list.html', context)



def contact(request):
    if request.method == "GET":
        return render(request, 'electrical.html')
    elif request.method== "POST":
        try:
            name = request.POST['name']
            email = request.POST['email']
            mobile = request.POST['mobile']
            message = request.POST['message']
            contact = Contacts(user_name=name, email=email, mobile_number=mobile, message=message)
            contact.save()
            print("name = " + name)
            return render(request, 'electrical.html', {'success' : True})
        except Exception as e:
            print("error in request")
            return  render(request, 'electrical.html', {'success': False})

def feedback(request):
    return render(request, 'contact.html')




# Create your views here.




# Create your views here.

shops/templates/contact.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }} {% else %} Josh Classicals {% endif %}
{% endblock %}
{% block content %}
<center>
<div class="contct"style="margin-top:9%">
    <div>
        <p>
            <h1><u>About Me</u></h1>
            <h4><u>I offer and make the following types of furniture</u></h4>

        <table style="">
            <tr>
                <td>
                   <p style="margin-left:450px">
                       <b> 1.Wall Units and Tv Stands</b>
                   </p>
                </td>
            <td>
                   <p style="margin-right:450px">
                       <b>2.Tables and Coffee Tables</b>
                   </p>
                </td>
            </tr>
 <tr>
                <td>
                   <p style="margin-left:450px">
                       <b> 3.Beds</b>
                   </p>
                </td>
            <td>
                   <p style="margin-right:450px">
                       <b>4.Dinning Tables</b>
                   </p>
                </td>
            </tr>
             <tr>
                <td>
                   <p style="margin-left:450px">
                       <b> 5.Shoe Ruck</b>
                   </p>
                </td>
            <td>
                   <p style="margin-right:450px">
                       <b>6.Chest of Drawer</b>
                   </p>
                </td>
            </tr>
             <tr>
                <td>
                   <p style="margin-left:450px">
                       <b> 7.Sofa Sets seats</b>
                   </p>
                </td>
            <td>
                   <p style="margin-right:450px">
                       <b>8.Home Fittings</b>
                   </p>
                </td>
            </tr>
             <tr>
                <td>
                   <p style="margin-left:450px">
                       <b> 9.Wardrobe</b>
                   </p>
                </td>
            <td>
                   <p style="margin-right:450px">
                       <b>10.Door Fitting</b>
                   </p>
                </td>
            </tr>
        </table>
<h4><u>I offer the following types of Skills and Services:</u></h4>
 <table style="">
            <tr>
                <td>
                   <p style="margin-left:450px">
                       <b> 1.Web system design and Development</b>
                   </p>
                </td>
            <td>
                   <p style="margin-right:450px">
                       <b>2.Drawing and Painting</b>
                   </p>
                </td>
            </tr>
 <tr>
                <td>
                   <p style="margin-left:450px">
                       <b> 3.Data Entry</b>
                   </p>
                </td>
            <td>
                   <p style="margin-right:450px">
                       <b>4.Data collection</b>
                   </p>
                </td>
            </tr>
             <tr>
                <td>
                   <p style="margin-left:450px">
                       <b> 5.Electrical Connection</b>
                   </p>
                </td>

            </tr>
 </table>
        <h1><u>Where to Find Me</u></h1>
        <h4><i>You can find me next to Cheers Hotel in Mlolongo Machakos County</i></h4>

    </div>
        <h1><u>You Can Reach Out To Me Personally Through:</u></h1>

    <div style="margin-top:15px;background-color:#77cde3">
               <ul>
    <li>My Mobile Number: 0715782132(Call or WhatsApp me)</li>
    <li>  My Email Address: joshenterprized@gmail.com</li>
        <li>  My Email Address: adejosh6759@gmail.com</li>
    <li>My Facebook Page:Josh Enterprises</li>
</ul>
        </div>
</div>
</center>

{% endblock %}

shops/templates/electrical.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }} {% else %} Josh Classicals {% endif %}
{% endblock %}
{% block content %}
    <div class="container">
        <div class="col-md-5">
            <div class="form-area">
                <form role="form" action="{% url 'shops:Contact' %}" method="post">
                    {% csrf_token %}
                    <br style="clear:both">
                    <h3 style="margin-bottom: 25px; text-align: center;">Contact Form</h3>
                    <div class="form-group">
                        <input type="text" class="form-control" id="name" name="name" placeholder="Name" required>
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" id="email" name="email" placeholder="Email" required>
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" id="mobile" name="mobile" placeholder="Mobile Number"
                               required>
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" id="subject" name="subject" placeholder="Subject"
                               required>
                    </div>
                    <div class="form-group">
                        <textarea class="form-control" type="textarea" id="message" name="message" placeholder="Message"
                                  maxlength="140" rows="7"></textarea>
                        <span class="help-block"><p id="characterLeft"
                                                    class="help-block ">You have reached the limit</p></span>
                    </div>

                    <button type="submit" id="submit" name="submit" class="btn btn-primary pull-right">Submit Form
                    </button>
                </form>
            </div>


            {% if  success %}
                <div class="row">
                    <p style="color: red">
                        feedback is send succesfully
                    </p>
                </div>
            {% endif %}

        </div>
    </div>

{% endblock %}

shops/templates/shop/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Josh Classicals{% endblock %}</title>
    <meta name="description" content="E-commerce App" />
  <meta name="keywords" content=" shop,buy,kenya" />

  <script src="{% static 'js/vendor/jquery-2.1.4.min.js' %}"></script>
  <script src="https://js.braintreegateway.com/js/braintree-2.27.0.min.js"></script>
  <link href="{% static 'css/vendor/socicon.min.css' %}" rel="stylesheet" media="screen">

  <link href="{% static 'css/vendor/bootstrap.min.css' %}" rel="stylesheet" media="screen">
  <link href="{% static 'css/theme.min.css' %}" rel="stylesheet" media="screen">
  <link href="{% static 'css/custom.css' %}" rel="stylesheet" media="screen">
  <link rel="shortcut icon" href="{% static 'josh.png'%}" type="image/x-icon">
  <link rel="icon" href="{% static 'josh.png' %}" type="image/x-icon">
  <link href="{% static 'css/vendor/material-icons.min.css' %}" rel="stylesheet" media="screen">
  <link rel="stylesheet"
    href="https://fonts.googleapis.com/css?family=Roboto:100,100italic,300,300italic,400,400italic,500,500italic">

  <script src="{% static 'js/vendor/jquery-2.1.4.min.js' %}"></script>
  <script src="https://js.braintreegateway.com/js/braintree-2.27.0.min.js"></script>
  <link href="{% static 'css/vendor/socicon.min.css' %}" rel="stylesheet" media="screen">

  <link href="{% static 'css/vendor/bootstrap.min.css' %}" rel="stylesheet" media="screen">
  <link href="{% static 'css/theme.min.css' %}" rel="stylesheet" media="screen">
  <link href="{% static 'css/custom.css' %}" rel="stylesheet" media="screen">
  <script src="{% static 'js/vendor/page-preloading.js' %}"></script>
  <script src="{% static 'js/vendor/modernizr.custom.js' %}"></script>
  <script src="{% static 'js/custom.js' %}"></script>
  <script src="{% static 'js/scripts.js' %}"></script>
</head>
<body class="page-preloading">

<style>
.top-left{
  position: absolute;
  top:1px;
  left:5px;
  border-radius:10px;
  font-color: black;
  font-size:35px;
  background-color:#FF00FF;
  }

.centered{
  position: absolute;
  color:black;
  top: 90%;
  left: 50%;
  transform: translate(-50%, -50%);
  }

</style>

 <header class="navbar navbar-sticky"style="height:130px;background-color:#ADD8E6">
      <nav class="main-navigation text-center">
 <button class="top-left"value="Josh Classicals"style="color:black">
                  <a href="{% url 'shops:Home' %}" class="site-logo visible-desktop" style="color:#77cde3;float:left;font-size:25px;margin- bottom:7px">
        <span class="grey"style="color:blue">Josh-</span><span style="color:black">Classicals</span>
      </a>
          </button>
        <ul class="menu">
          <li class="top-left"style="color:blue;font-type:bold;margin-bottom:15px">

          </li>
          <li><a href="{% url 'shops:Home' %}">Home</a></li>
          <li class="menu-item-has-children current-menu-item">
            <a href="#">Shop</a>
            <ul class="sub-menu">
               <li class="current-menu-item"><a href="shop-fullwidth-sl.html">Categories</a></li>
              {% for c in categories %}

              <li {% if category.slug == c.slug %} class="active"{% endif %}>
                  <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
              </li>
            {% endfor %}

            </ul>
          </li>
          <li><a href="{% url 'shops:reach' %}">About Me</a></li>
           <li><a href="{% url 'shops:Contact' %}">Report Problem</a></li>
          <li class="menu-item-has-children current-menu-item">
            <a href="#">Owino Technologies</a>
               <ul class="sub-menu">
                   <li class="current-menu-item">Coming Soon</li>
          </li>

            </ul>
          </li>
        </ul>
      </nav>
 <div class="toolbar"style="top:5px">
        <div class="inner"style="top:5px">
 <a href="#" class="mobile-menu-toggle"><i class="material-icons menu"></i></a>
          <img src="{% static 'img/josh1.jpg' %}"width="80px"height="120px">
        </div></div>

     <div class="centered">

          <div class="shop-bar">
            <div class="column">
              <form method="get" class="search-box">
                <input id="search" type="text" class="form-control" placeholder="Search By Furniture Name">
                <button type="submit">
                  <i class="material-icons search"></i>
                </button>
              </form>
            </div>
          </div></div>
 </header>
    {% if messages %}
    <div class="row callout" class="fw-section bg-gray ">
      <div class="col-md-6 col-md-offset-4">
        <div class="row">
          {% for message in messages %}
          <div class="container-fluid">
            {% if message.tags == 'success' %}
            <div class="col-sm-2" style="background: #63D3E9;width: 60px;height: 50px;color:#fff;"><i
                class="material-icons" style="font-size:2em;padding-top:10px;text-align: center;">thumb_up</i></div>
            <div class="col-sm-10" style="color:#fff;background:#c6f3fb;height: 50px;">{{message}}</div>
            {% else %}
            <div class="col-sm-2 " style="background:#f36a5a;width: 60px;height: 50px;color:#fff;"><i
                class="material-icons" style="font-size:2em;padding-top:10px;text-align: center;">warning</i></div>
            <div class="col-sm-10" style="color:#fff;background-color:#ffb5ad;height: 50px;">{{message}}</div>
            {% endif %}
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
    {% endif %}</div>



{% block content %}


{% endblock %}
<footer class="footer">
    <div class="column">
      <p class="text-sm">Need support? Call <span class="text-primary">+254 715 782 132</span></p>
      <div class="social-bar text-center space-bottom">
        <a href="#" class="sb-skype" data-toggle="tooltip" data-placement="top" title="Skype">
          <i class="socicon-skype"></i>
        </a>
        <a href="#" class="sb-facebook" data-toggle="tooltip" data-placement="top" title="Facebook">
          <i class="socicon-facebook"></i>
        </a>
        <a href="#" class="sb-google-plus" data-toggle="tooltip" data-placement="top" title=""
          data-original-title="Google+">
          <i class="socicon-googleplus"></i>
        </a>
        <a href="#" class="sb-twitter" data-toggle="tooltip" data-placement="top" title="Twitter">
          <i class="socicon-twitter"></i>
        </a>
        <a href="#" class="sb-instagram" data-toggle="tooltip" data-placement="top" title=""
          data-original-title="Instagram">
          <i class="socicon-instagram"></i>
        </a>
      </div>
      {% now "Y" as current_year %}
      <p class="copyright">&copy; {{ current_year }}. Developed by <i class="text-danger material-icons favorite"></i> by
        Owino Technologies</p>

    </div>
    <div class="column">
      <h3 class="widget-title">
        Subscription
        <small>To receive latest offers and discounts from the shop.</small>
      </h3>
      <form action="." class="subscribe-form" novalidate>
        <input type="email" class="form-control" name="EMAIL" placeholder="Your e-mail">

        <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text"
            name="b_c7103e2c981361a6639545bd5_1194bb7544" tabindex="-1" value=""></div>
        <button type="submit"><i style="padding-top:8px;" class="material-icons send"></i></button>
      </form>
    </div>
    <div class="column">
      <h3 class="widget-title">
        Payment Methods
        <small>We support one of the following payment methods.</small>
      </h3>
      <div class="cards"><img src="{% static 'img/cards.png'%}" alt="Cards">Mpesa</div>

      <div class="scroll-to-top-btn"><i class="material-icons trending_flat"></i></div>
    </div>
  </footer>

  </div>


  <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/vendor/smoothscroll.js' %}"></script>
  <script src="{% static 'js/vendor/velocity.min.js' %}"></script>
  <script src="{% static 'js/vendor/waves.min.js' %}"></script>
  <script src="{% static 'js/vendor/icheck.min.js' %}"></script>
  <script src="{% static 'js/vendor/nouislider.min.js' %}"></script>
  <script src="{% static 'js/scripts.js' %}"></script>
  <script src="{% static 'js/custom.js' %}"></script>

<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
</body>
</html>

shops/templates/shop/product/detail.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }} {% else %} Josh Classical Furnitures {% endif %}
{% endblock %}

{% block content %}
   <div class="container">
      <div class="row" style="margin-top: 8%;">

        <div class="col-sm-8 blog-main">

          <div class="blog-post"style="height:500px;width:1000px">
              <div class="row"style="height:500px;width:1000px" >
                <div class="card"style="height:500px;width:1200px">
                    <div class="card-body"style="height:500px;width:1200px">
                        <div class="col-md-6 text-right"style="height:500px;width:1200px">
                            <img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" alt="..." style="height: 450px; width: 650px">
                        </div>
                        <div class="col-md-6" style="padding-left: 20px">
                            <h3>{{ product.name }}</h3>
                            <h6><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h6>
                            <p class="text-muted">Kshs. {{ product.price }}</p>
                            <form action="{% url 'cart:cart_add' product.id %}" method="post">
                                {% csrf_token %}
                                {{ cart_product_form }}
                                <input type="submit" value="add to cart" class="btn btn-primary">
                            </form>
                            <p>{{ product.description|safe|linebreaksbr }}</p>
                        </div>
                    </div>
                </div>
              </div>


          </div><!-- /.blog-post -->

        </div><!-- /.blog-main -->
      </div><!-- /.row -->

    </div><!-- /.container -->
{% endblock %}